kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    certSANs:
      - "host.docker.internal"
      - "127.0.0.1"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6443
        listenAddress: "0.0.0.0"
